package dev.arglabs.tubego;
import android.os.Bundle;import android.content.*;import android.widget.*;
public final class HelpActivity extends LocalizedActivity {
 @Override public void onCreate(Bundle state){super.onCreate(state);LinearLayout layout=new LinearLayout(this);layout.setOrientation(LinearLayout.VERTICAL);layout.setPadding(32,48,32,32);
  TextView title=new TextView(this);title.setText(Texts.text(this,"Ayuda de Tubego"));title.setTextSize(24);layout.addView(title);
  paragraph(layout,"Agrega un enlace pegándolo o compartiéndolo desde otra app. Elige calidad o solo audio. El servidor prepara el archivo y tus dispositivos lo descargan automáticamente por Wi-Fi; cada usuario tiene su biblioteca privada.");
  paragraph(layout,"Si se pierde Wi-Fi, la descarga se pausa y continúa desde donde quedó al regresar. Puedes autorizar datos móviles para un único archivo en este teléfono; no autoriza otros videos ni dispositivos. Los enlaces y acciones pequeñas pueden usar cualquier conexión.");
  paragraph(layout,"Los archivos descargados permanecen en el teléfono hasta que los borres. Si falta espacio, la app pausa las descargas y te avisa, sin borrar contenido automáticamente. Android puede demorar el trabajo en segundo plano; si fuerzas el cierre de Tubego, abre la app para reanudarlo.");
  paragraph(layout,"Puedes reproducir sin conexión con VLC u otro reproductor instalado. En VLC configura el modo de segundo plano o PiP y autoriza la ventana flotante. Para escuchar con la pantalla bloqueada, usa la opción de reproducir como audio o el modo de audio en segundo plano. Las funciones y los gestos dependen de tu reproductor; Tubego no reproduce ni descarga otra copia al abrir un archivo local.");
  paragraph(layout,"El historial conserva el enlace, la ficha y el último abierto aunque ya no exista el archivo. Buscar, filtrar, cancelar, reintentar y poner un video como siguiente se hacen desde Biblioteca. La prioridad nunca interrumpe la descarga actual. Si un archivo fue borrado a propósito, se pedirá aprobación antes de recuperarlo.");
  paragraph(layout,"Guardar el minuto exacto donde te quedaste depende de la investigación de compatibilidad con VLC. No está garantizado. Si se consigue, el retroceso al continuar será el de tus preferencias: diez segundos inicialmente, configurable por usuario.");
  paragraph(layout,"Al borrar puedes elegir tus dispositivos o tus dispositivos y el servidor. El borrado se sincroniza; equipos desconectados lo aplican al reconectar. Limpiar el servidor no borra tus copias locales ni el historial. Si una orden queda pendiente se envía al recuperar conexión.");
  paragraph(layout,"Al cerrar sesión se borran las descargas de ese teléfono con confirmación. Puedes cerrar sesiones o desvincular dispositivos desde Mi cuenta. Bloquear o eliminar una cuenta revoca el acceso y ordena borrar sus archivos al próximo contacto; las copias exportadas a otras apps quedan fuera del control de Tubego.");
  paragraph(layout,"Un administrador aprueba cuentas después de verificar el correo. Solo administradores cambian prioridades de usuarios, conservación, plazos, limpieza global y mantenimiento. Si no se conservan archivos en el servidor, se borran cuando todos los dispositivos confirman la descarga o al vencer el plazo: inicialmente cuatro horas desde la primera entrega y como máximo tres días desde que quedó listo. Los administradores pueden cambiar esos plazos para todos los archivos existentes.");
  paragraph(layout,"La velocidad del servidor se mide desde Administración; no descarga una prueba grande en tu teléfono. Diagnóstico muestra la conexión y tus avisos; no comparte contraseñas, tokens ni registros privados de otras cuentas. El bot de Telegram sigue funcionando con una lista independiente.");
  button(layout,"Idioma",LanguageActivity.class);button(layout,"Diagnóstico de esta cuenta",DiagnosticsActivity.class);
  ScrollView scroll=new ScrollView(this);scroll.addView(layout);setContentView(scroll);
 }
 private void paragraph(LinearLayout layout,String source){TextView text=new TextView(this);text.setText(Texts.text(this,source));text.setPadding(0,16,0,16);layout.addView(text);}
 private void button(LinearLayout layout,String source,Class<?> target){Button button=new Button(this);button.setText(Texts.text(this,source));button.setOnClickListener(v->startActivity(new Intent(this,target).putExtra("server_url",LanguagePreferences.origin(this))));layout.addView(button);}
}
