package dev.arglabs.tubego;
import android.app.Activity;
import android.app.AlertDialog;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.widget.*;
import org.json.*;
import java.util.concurrent.*;

/** Administrative operations are server jobs; reconnecting never means assumed success. */
public final class MaintenanceActivity extends Activity {
    private final ExecutorService network=Executors.newSingleThreadExecutor();
    private final java.util.concurrent.atomic.AtomicBoolean refreshing=new java.util.concurrent.atomic.AtomicBoolean();
    private final Handler handler=new Handler(Looper.getMainLooper());
    private LinearLayout layout;private TextView message;private String origin;private JSONObject snapshot;private boolean active;
    private final Runnable poll=new Runnable(){@Override public void run(){if(active){refresh();handler.postDelayed(this,5000);}}};
    @Override public void onCreate(Bundle state){super.onCreate(state);layout=new LinearLayout(this);layout.setOrientation(LinearLayout.VERTICAL);layout.setPadding(24,48,24,24);message=new TextView(this);layout.addView(message);ScrollView scroll=new ScrollView(this);scroll.addView(layout);setContentView(scroll);
        try{origin=new ApiClient(getIntent().getStringExtra("server_url")).getBaseUrl();JSONObject session=new SessionStore(this,origin).read();if(session==null||!"admin".equals(session.optString("role"))||!"approved".equals(session.optString("status"))){message.setText("Se requiere una cuenta de administrador aprobada.");origin=null;return;}snapshot=MaintenanceCommands.cached(this,origin);render();}catch(Exception e){message.setText("No se pudo abrir la administración.");}}
    private void button(String text,Runnable action,boolean enabled){Button b=new Button(this);b.setText(text);b.setEnabled(enabled);b.setOnClickListener(v->action.run());layout.addView(b);}
    private void render(){layout.removeAllViews();layout.addView(message);JSONObject installed=snapshot==null?null:snapshot.optJSONObject("installed");message.setText("Mantenimiento del servidor\n"+(installed==null?"Conecta para consultar las versiones.":"Tubego: "+installed.optString("tubego")+"\nyt-dlp: "+installed.optString("yt_dlp")+"\nRevisión: "+installed.optString("backend_revision")));
        button("Actualizar estado",this::refresh,true);button("Consultar versiones disponibles",()->enqueue("check_versions",null,null,false),true);button("Medir velocidad del servidor",()->confirm("La medición descarga 5 MB en el servidor. El teléfono recibe solo el resultado.",()->enqueue("speed_test",null,null,true)),true);
        JSONObject caps=snapshot==null?null:snapshot.optJSONObject("capabilities");boolean enabled=caps!=null&&caps.optBoolean("mutation_enabled");if(!enabled){TextView reason=new TextView(this);reason.setText("Actualizar y reiniciar requieren un supervisor habilitado por el operador del despliegue.");layout.addView(reason);}
        button("Actualizar backend",()->choose("backend_revisions","update_backend"),enabled);button("Actualizar yt-dlp",()->choose("yt_dlp_versions","update_ytdlp"),enabled);button("Reiniciar servicio",()->confirm("Se esperará a que terminen las descargas del servidor. ¿Reiniciar el servicio?",()->enqueue("restart",null,null,true)),enabled);
        if(snapshot!=null){JSONObject versions=snapshot.optJSONObject("versions");if(versions!=null){TextView v=new TextView(this);v.setText("Versiones disponibles: "+describe(versions));layout.addView(v);}JSONArray jobs=snapshot.optJSONArray("jobs");if(jobs!=null)for(int i=jobs.length()-1;i>=0;i--){JSONObject job=jobs.optJSONObject(i);TextView v=new TextView(this);v.setText(actionLabel(job.optString("action"))+" · "+stateLabel(job.optString("status"))+"\n"+(job.isNull("result")?errorLabel(job.optString("error_code")):describe(job.optJSONObject("result"))));layout.addView(v);}}
        try{JSONObject last=MaintenanceCommands.last(this,origin);if(last!=null&&!last.has("id")){TextView v=new TextView(this);v.setText("Última solicitud: "+errorLabel(last.optString("error_code")));layout.addView(v);}}catch(Exception ignored){}
    }
    private static String actionLabel(String value){return switch(value){case "check_versions"->"Consulta de versiones";case "speed_test"->"Velocidad del servidor";case "update_backend"->"Actualización de Tubego";case "update_ytdlp"->"Actualización de yt-dlp";case "restart"->"Reinicio del servicio";default->"Mantenimiento";};}
    private static String stateLabel(String value){return switch(value){case "queued"->"Pendiente";case "waiting_worker"->"Esperando descargas activas";case "running"->"En curso";case "succeeded"->"Completado";case "failed"->"Falló";default->"Estado pendiente";};}
    private static String errorLabel(String code){if(code.isEmpty()||code.equals("null"))return "";return switch(code){case "capability_unavailable"->"El despliegue no tiene mantenimiento habilitado.";case "administrator_session_unavailable"->"La sesión de administrador ya no está disponible.";case "deployment_verification_failed","supervisor_command_failed","operation_failed"->"No se pudo verificar el servicio. El operador debe revisar el despliegue.";case "operator_recovered_interrupted_operation"->"El operador recuperó el servicio; la operación anterior quedó interrumpida.";default->"No se pudo completar la operación. Revisa los permisos o la configuración del servidor.";};}
    private static String describe(JSONObject result){if(result==null)return "";if(result.has("server_download_mbps"))return "Descarga del servidor: "+result.optDouble("server_download_mbps")+" Mbps (5 MB)";JSONObject available=result.optJSONObject("available");JSONObject installed=result.optJSONObject("installed");JSONObject values=available!=null?available:installed;return values==null?"": "yt-dlp: "+values.optString("yt_dlp")+"\nRevisión Tubego: "+values.optString("backend_revision");}
    private void choose(String field,String action){JSONArray choices=snapshot.optJSONObject("capabilities").optJSONArray(field);if(choices==null||choices.length()==0){message.setText("No hay versiones aprobadas por el operador.");return;}String[] values=new String[choices.length()];for(int i=0;i<values.length;i++)values[i]=choices.optString(i);new AlertDialog.Builder(this).setTitle("Versión aprobada").setItems(values,(d,w)->confirm("Actualizar a "+values[w]+". Se esperará a las descargas activas y se comprobará el servicio al terminar.",()->enqueue(action,action.equals("update_backend")?values[w]:null,action.equals("update_ytdlp")?values[w]:null,true))).setNegativeButton("Cancelar",null).show();}
    private void confirm(String text,Runnable yes){new AlertDialog.Builder(this).setMessage(text).setNegativeButton("Cancelar",null).setPositiveButton("Confirmar",(d,w)->yes.run()).show();}
    private void enqueue(String action,String revision,String version,boolean confirmed){try{JSONObject command=new JSONObject().put("action",action).put("confirmed",confirmed);if(revision!=null)command.put("revision",revision);if(version!=null)command.put("version",version);MaintenanceCommands.enqueue(this,origin,command);message.setText("Solicitud guardada. Se enviará cuando haya conexión.");refresh();}catch(Exception e){message.setText("No se pudo guardar: verifica tu sesión o espera a que se envíe la solicitud pendiente.");}}
    private void refresh(){if(origin==null||!refreshing.compareAndSet(false,true))return;network.execute(()->{try{MaintenanceCommands.flush(this,origin);JSONObject session=new SessionStore(this,origin).read();if(session==null)return;JSONObject value=new ApiClient(origin).request("GET","/admin/maintenance",null,session.getString("token"));MaintenanceCommands.cache(this,origin,session,value);runOnUiThread(()->{if(!isDestroyed()){try{if(MaintenanceCommands.same(session,new SessionStore(this,origin).read())){snapshot=value;render();}else{snapshot=null;layout.removeAllViews();layout.addView(message);message.setText("La sesión cambió. Abre nuevamente la administración.");}}catch(Exception ignored){}}});}catch(Exception e){runOnUiThread(()->{if(!isDestroyed())message.setText("Sin conexión o servicio reiniciándose. La solicitud conserva su identificador; consulta su estado al recuperar conexión.");});}finally{refreshing.set(false);}});}
    @Override protected void onResume(){super.onResume();active=origin!=null;if(active){try{snapshot=MaintenanceCommands.cached(this,origin);render();}catch(Exception ignored){}handler.post(poll);}}
    @Override protected void onPause(){active=false;handler.removeCallbacksAndMessages(null);super.onPause();}
    @Override protected void onDestroy(){network.shutdownNow();super.onDestroy();}
}
