package dev.arglabs.tubego;
import android.content.Context;
/** Looks up resource literals, never rewrites user titles, URLs, credentials or protocol values. */
public final class Texts {
 public static String text(Context context,String source){Context localized=context instanceof LocalizedActivity?((LocalizedActivity)context).textContext():LanguagePreferences.localized(context,LanguagePreferences.language(context,LanguagePreferences.origin(context)));int id=localized.getResources().getIdentifier(TextKey.of(source),"string",context.getPackageName());return id==0?source:localized.getString(id);}
 public static String forOrigin(Context context,String origin,String source){Context localized=LanguagePreferences.localized(context,LanguagePreferences.language(context,origin));int id=localized.getResources().getIdentifier(TextKey.of(source),"string",context.getPackageName());return id==0?source:localized.getString(id);}
 public static String[] labels(Context context,String[] values){String[] translated=values.clone();for(int i=0;i<translated.length;i++)translated[i]=text(context,translated[i]);return translated;}
 public static String error(Context context,Throwable error){if(error instanceof ApiClient.ApiException){ApiClient.ApiException e=(ApiClient.ApiException)error;switch(e.code){case "session_revoked":case "account_unavailable":return text(context,"Tu sesión fue revocada o tu cuenta no está disponible.");case "session_expired":return text(context,"Tu sesión venció. Inicia sesión nuevamente.");case "unsupported_url":return text(context,"Este enlace no es compatible con las plataformas disponibles.");}if(MediaFailureText.known(e.code))return failure(context,e.code);if(e.status==401||e.status==403)return text(context,"Revisa tu sesión y tus permisos.");if(e.status==429)return text(context,"Demasiados intentos. Espera antes de volver a intentar.");}String message=error.getMessage();if(message!=null&&context.getResources().getIdentifier(TextKey.of(message),"string",context.getPackageName())!=0)return text(context,message);return text(context,"No se pudo completar. Revisa los datos y la conexión.");}
 public static String state(Context context,String code){switch(code){case "pending_verification":return text(context,"Correo sin verificar");case "pending_approval":return text(context,"Pendiente de aprobación");case "approved":return text(context,"Aprobado");case "blocked":return text(context,"Bloqueado");case "rejected":return text(context,"Rechazado");case "deleted":return text(context,"Borrado");case "admin":return text(context,"Administrador");case "user":return text(context,"Usuario");case "queued":case "pending":return text(context,"Pendiente");case "running":case "downloading":return text(context,"Descargando");case "paused":case "retry_wait":return text(context,"Pausado");case "failed":case "error":return text(context,"Error");case "complete":case "completed":return text(context,"Completado");case "cancelled":return text(context,"Cancelado");case "ready":return text(context,"Listo");case "analyzing":return text(context,"Analizando");case "postprocessing":return text(context,"Preparando archivo");case "approval_required":return text(context,"Requiere aprobación para volver a descargar");case "server_storage":case "device_storage":return text(context,"Espacio insuficiente");default:return text(context,"Estado no disponible");}}
 public static String quality(Context context,String value){try{return labels(context,MediaSelection.LABELS)[MediaSelection.index(value)];}catch(Exception ignored){return text(context,"Calidad no válida");}}
 public static String failure(Context context,String code){return text(context,MediaFailureText.source(code));}
 public static String qualityNotice(Context context,String code){String source=QualityNoticeText.source(code);return source.isEmpty()?"":text(context,source);}
 public static String command(Context context,String kind){String label;switch(kind){case "submit":label="Agregar enlace · Tubego";break;case "recover":label="Volver a solicitar archivo";break;case "delete":label="Borrar archivos";break;case "server_cleanup":label="Limpiar archivos del servidor";break;case "resource_priority":label="Priorizar archivo";break;case "preferences":label="Preferencias";break;case "language":label="Idioma";break;case "task_cancel":label="Cancelar descarga del servidor";break;case "task_retry":label="Reintentar descarga del servidor";break;default:label="Acción pendiente";}return text(context,label);}
 public static String commandError(Context context,String error){if(error.endsWith("approval_required"))return text(context,"Requiere aprobación para volver a descargar");if(error.endsWith("invalid_command"))return text(context,"La solicitud no es válida. Revisa sus datos antes de repetirla.");return text(context,"Acción rechazada. Revisa los permisos y el estado del recurso antes de volver a solicitarla.");}
}
