plugins { id 'com.android.application' }
android {
    namespace 'dev.arglabs.tubego'
    compileSdk 35
    useLibrary 'android.test.runner'
    useLibrary 'android.test.base'
    useLibrary 'android.test.mock'
    defaultConfig {
        applicationId 'dev.arglabs.tubego'
        minSdk 29
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies { testImplementation 'junit:junit:4.13.2' }
